### ISSUE TITLE
강민님!!

### ISSUE THREAD

**Issue by kkogggokk** [cjsrkd3321/getting-started-with-docker-and-containers#1]
이벤트 페이지에서 <이전 응답 참조> 버튼 누르면 설문 기재된 내용들이 다 노출되고 있습니다!🥲
<img width="482" alt="스크린샷 2024-07-12 오후 5 44 14" src="https://github.com/user-attachments/assets/e552ecbd-d562-4133-b4e4-d98561db01f9">

**Comment by kkogggokk** [comment]
> 이벤트 페이지에서 <이전 응답 참조> 버튼 누르면 설문 기재된 내용들이 다 노출되고 있습니다!🥲 <img alt="스크린샷 2024-07-12 오후 5 44 14" width="482" src="https://private-user-images.githubusercontent.com/68055218/348251269-e552ecbd-d562-4133-b4e4-d98561db01f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3ODUyNDAsIm5iZiI6MTcyMDc4NDk0MCwicGF0aCI6Ii82ODA1NTIxOC8zNDgyNTEyNjktZTU1MmVjYmQtZDU2Mi00MTMzLWI0ZTQtZDk4NTYxZGIwMWY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEyVDExNDkwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkNzA4NmRiMTgzM2FhZDlmZjRiNGNlOGFhN2Q2NGYxMGEzYTliOTQ5NmUyZDViNDVjZDkyZDY4ZDAyODNmNWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zN0wS4j0d3Odwv2d_n7nBG5P7W-c0gE09-L1NS4M-4Y">

**Comment by cjsrkd3321** [comment]
메일 감사드립니다. 요약 제공을 켜놨네요 ㅠ 수정했습니다!!!

2024년 7월 12일 (금) 오후 8:49, KOG ***@***.***>님이 작성:

**Comment by kkogggokk** [comment]
휴! 위에 내용 삭제하셔도  괜찮습니다!
